In [3]:
import numpy as np

In [4]:
array = np.array([2,1,4,6,7,0])

print(array)

[2 1 4 6 7 0]


In [7]:
# 2D array

array = np.array([[2,3,4],[4,6,8]])
print(array)

print(array.ndim)

[[2 3 4]
 [4 6 8]]
2


In [9]:
# 3D Array

array =np.array([[[2,3,4],[2,5,7]],[[2,3,9],[9,0,0]]])
print(array)


[[[2 3 4]
  [2 5 7]]

 [[2 3 9]
  [9 0 0]]]


In [12]:
# 0-D

array = np.array(3)
print(array)
print(array.ndim)

3
0


In [14]:
# Accessing 1D array element

array = np.array([3,45,67,44,10])

# accessing 4th element
print(array[3])


44


In [18]:
#accessing 2D array element 

array = np.array([[2,4,6,8,78],[4,1,2,45,34]])
print(array[0][-1])
print(array[0,-1])


78
78


In [29]:
# 3D Array

array =np.array([[[2,3,4],[2,5,7]],[[2,3,9],[9,0,0]]])
# print(array)

print(array)

2


In [32]:
# slicing array
array = np.array([3,45,67,44,10,67,98,33,60])

print(array[0:6:2])


[ 3 67 10]


## checking datatypes


In [38]:
import numpy as np

array = np.array([3,45,67,44,10,67,98,33,60],dtype='i')
print(array)


[ 3 45 67 44 10 67 98 33 60]


In [42]:
# creating datatypes with defined datatypes and size

import numpy as np

array = np.array([3,45,67,44,10,67,98,33,60],dtype='i')
print(array.dtype)
print(array.shape)

int32
(9,)


In [43]:
array = np.array([[2,4,6,8,78],[4,1,2,45,34]])

print(array.shape)

(2, 5)


In [48]:
array =np.array([[[2,3,4],[2,5,7],[3,45,7]],
                 [[2,3,9],[9,0,0],[6,76,69]]])

print(array.shape)

(2, 3, 3)


In [53]:
# # reshape array
# array = np.array([3,45,67,44,10,67,98,33,60,8])
# print(array)

# array = np.reshape(array,(2,2))

import numpy as np

array1 = np.array([1, 3, 5, 7, 2, 4, 6, 8])

# reshape a 1D array into a 2D array 
# with 2 rows and 4 columns

result = np.reshape(array1, (2, 4))
print(result)


[[1 3 5 7]
 [2 4 6 8]]


#### Generate 1-D array contaning 5 random integers from 0 to 59


In [58]:
import random
 
x = random.randint(100)


TypeError: randint() missing 1 required positional argument: 'b'