## Basics of Array

Import Numpy

In [1]:
import numpy

In [2]:
array = numpy.array([1,2,3,4,5,6,7,8])
print(array)

[1 2 3 4 5 6 7 8]


Import Numpy as np

In [3]:
import numpy as np

Checking numpy version

In [4]:
print(np.__version__)

1.26.2


Use tuple to create numpy Array

In [5]:
array = np.array((1,2,3,4,5))
print(array)

[1 2 3 4 5]


0 Dimension Array or Scalar

In [6]:
import numpy as np

array = np.array(21)
print(array)

21


In [7]:
# Printing Dimension of Array
print(array.ndim)

0


2-D Array or Uni Dimensional Array

In [8]:
array = np.array([[2,4,6,8],[1,3,5,7]])
print(array)
print('dimension of 2D array is:{}'.format(array.ndim))



[[2 4 6 8]
 [1 3 5 7]]
dimension of 2D array is:2


3-D array

In [9]:
array = np.array([[[1,2,3],[2,3,4]],[[5,6,7],[3,3,5]]])

print(array)
print(array.shape)
print('dimension of 3D array is:{}'.format(array.ndim))

[[[1 2 3]
  [2 3 4]]

 [[5 6 7]
  [3 3 5]]]
(2, 2, 3)
dimension of 3D array is:3


## Array Indexing

Accessing 1-D Array

In [10]:
import numpy as np


In [11]:
arr = np.array([1,2,3,4,5,6])
print(arr)

# 1st element
print(arr[0])

# get 5th element
print(arr[4])

[1 2 3 4 5 6]
1
5


Accessing 2-D Array

In [12]:
import numpy as np

arr = np.array([[2,3,4,5,6], [1,2,8,9,0]])
print(arr)

# 1st 1-D array
print(arr[0])

# 1st element of 2nd 1-D array
print(arr[1][0])
# or
print(arr[1,0])

[[2 3 4 5 6]
 [1 2 8 9 0]]
[2 3 4 5 6]
1
1


Acessing 3D Array

In [13]:
import numpy as np
arr = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]])

print('shape :{}'.format(arr.shape))

# Accessing 1st 2-D Array
print(arr[0])

# Accessing 2nd 1-D Array of 1st 2-D Array
print(arr[0][1])

# Accessing 3rd element of 2nd 1-D array of 1st 2-D Array
print(arr[0][1][2])
print(arr[0,1,2])

shape :(2, 2, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 6  7  8  9 10]
8
8


Negative Indexing

In [14]:
import numpy as np
arr = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]])
print(arr)

# Accessing 1st 2-D Array
print(arr[-2])

# Accessing 2nd 1-D Array of 1st 2-D Array
print(arr[-2][-1])

# Accessing 3rd element of 2nd 1-D array of 1st 2-D Array
print(arr[-2][-1][-3])

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 6  7  8  9 10]
8


## Array Slicing

Slicing 1-D Array

In [15]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr[0:2])
print(arr[0:4:2])
print(arr[2:])
print(arr[:4])
print(arr[:])
"""
This code demonstrates various slicing operations on a NumPy array.

- arr[0:2]: Returns the elements at index 0 and 1 of the array.
- arr[0:4:2]: Returns the elements at index 0 and 2 of the array.
- arr[2:]: Returns all elements starting from index 2 to the end of the array.
- arr[:4]: Returns all elements from the beginning of the array up to index 3.
- arr[:]: Returns all elements of the array.

"""

[1 2]
[1 3]
[3 4 5]
[1 2 3 4]
[1 2 3 4 5]


'\nThis code demonstrates various slicing operations on a NumPy array.\n\n- arr[0:2]: Returns the elements at index 0 and 1 of the array.\n- arr[0:4:2]: Returns the elements at index 0 and 2 of the array.\n- arr[2:]: Returns all elements starting from index 2 to the end of the array.\n- arr[:4]: Returns all elements from the beginning of the array up to index 3.\n- arr[:]: Returns all elements of the array.\n\n'

Slicing 2-D Array

In [16]:
import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,17,182,29,310]])
print(arr[0][0:3])
"""
display the elements from the first row of 'arr', starting from index 0 up to index 2.
"""


[1 2 3]


"\ndisplay the elements from the first row of 'arr', starting from index 0 up to index 2.\n"

slicing 3-D array

In [17]:
import numpy as np

arr = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]])
print(arr[0][1][0:3])

[6 7 8]


Slicing 3-D Array

In [18]:
import numpy as np
arr = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]])
print(arr[0][1][0:3])

[6 7 8]


## Reshaping Array


1-D to 2-D

In [19]:
import numpy as np

array1 = np.array([1, 3, 5, 7, 2, 4, 6, 8])

# reshape a 1D array into a 2D array 
# with 2 rows and 4 columns
result = np.reshape(array1, (2, 4))
print(result)

[[1 3 5 7]
 [2 4 6 8]]


1-D to 3-D

In [20]:
import numpy as np

# create a 1D array
array1 = np.array([1, 3, 5, 7, 2, 4, 6, 8])

# reshape the 1D array to a 3D array
# reshapes array1 into a 3D array with 2 rows, 2 columns and 2 layers.
result = np.reshape(array1, (2, 2, 2))

# print the new array
print(result)

[[[1 3]
  [5 7]]

 [[2 4]
  [6 8]]]


Flattern 1D Array

In [21]:
import numpy as np

# flatten 2D array to 1D
array1 = np.array([[1, 3], [5, 7], [9, 11]])
result1 = np.reshape(array1, -1)
print(result1)

# flatten 3D array to 1D
array2 = np.array([[[1, 3], [5, 7]], [[2, 4], [6, 8]]])
result2 = np.reshape(array2, -1)
print(result2)


[ 1  3  5  7  9 11]
[1 3 5 7 2 4 6 8]


## Random element in array


Generate a 1-D array containing 5 random integers from 0 to 100:

In [22]:
from numpy import random

# Generates a random array of integers between 0 and 99.

x = random.randint(100, size=(5))
print(x)


[73 94 52 95  5]


In [24]:
x = np.arange(-10,10,2)
"""
Create a 1-dimensional array of numbers ranging from -10 to 10 (exclusive), with a step size of 2.
"""


'\nCreate a 1-dimensional array of numbers ranging from -10 to 10 (exclusive), with a step size of 2.\n'